[simulation]
name = "test"
calculation = "complex_corr"
corr_type = "asymm"
method = "adaptive-kinks-QuAPI"
output = "test.hdf5"

nsteps = 4
dt = 0.25
tfinal = 15.0

A = "sigmaz"
B = "sigmaz"
partition_function = "id"
fourier_transform = true
